### ISSUE TITLE
Globalise colour definitions 

### ISSUE THREAD

**Issue by MarcDenman** [UKHO/ADM-PSmodule#19]
The colour for each action (add, remove, modify etc.) aren't defined globally anywhere. It would make sense to have the colour defined once in a variable and then use that variable everywhere else.

**Comment by elduddz** [comment]
Wondering, these colours are only used by object.ps1. 

I wonder if they could be set there and then returned as a property value 

Or 

set as a hash object that is passed into functions as a control set

**Comment by elduddz** [comment]
You could add it to the configdata object that is passed into update-ad

**Comment by elduddz** [comment]
closed by #29
